language: go
go_import_path: github.com/constabulary/kodos
go:
  - 1.9.x
  - tip

sudo: false

install:
  - true

script:
  - go build -o $HOME/kodos -v github.com/constabulary/kodos/cmd/kodos
  - $HOME/kodos
  - $HOME/kodos
